twillio:
  api:
    key: ${TWILLIO_API_KEY}
  from: ${TWILLIO_FROM_EMAIL}

server:
  port: 8085
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: payments
